---
- hosts: NetTest
  tasks:
  - name: enable IPv4 precedence
    shell: echo precedence ::ffff:0:0/96  100 >> /etc/gai.conf
  - name: install zabbix-agent
    apt: name=zabbix-agent state=latest update_cache=yes
  - name: install zabbix-agent conf
    copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
    notify:
    - restart zabbix-agent
  - name: ensure zabbix-agent is running
    service: name=zabbix-agent state=started
  handlers:
  - name: restart zabbix-agent
    service: name=zabbix-agent state=restarted